# Database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/financeapp
spring.datasource.username=financeuser
spring.datasource.password=financepass123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Server
server.port=8080


#plaid
plaid.client-id=69fe5f1eee876c000e7c35e1
plaid.secret=30298576c06951fdd5d284d89e282e
plaid.env=sandbox